#pragma once

#include <string_view>

namespace tradeengine::hkex {

// ---------------------------------------------------------------------------
// Feed-format tag and symbol-prefix constants (HKEX DDS wire format)
// ---------------------------------------------------------------------------
inline constexpr std::string_view kTickerPrefix = "TICKER_";

inline constexpr std::string_view kTagImage     = "image";
inline constexpr std::string_view kTagUpdate    = "update";
inline constexpr std::string_view kTagListSetup = "listsetup";

inline constexpr std::string_view kPfxExch    = "EXCH_";
inline constexpr std::string_view kPfxTurn    = "TURN";
inline constexpr std::string_view kPfxOdd     = "ODD";
inline constexpr std::string_view kPfxNews    = "NEWS";
inline constexpr std::string_view kPfxSpread  = "SPREAD";

// ---------------------------------------------------------------------------
// OMS attribute identifiers used by the HKEX DDS feed.
// Values mirror the original omsConst.h in the legacy mds project.
// ---------------------------------------------------------------------------
enum : int {
    OMS_SYMBOL          = 0,
    OMS_BID             = 1,
    OMS_OFFER           = 2,
    OMS_L_PRICE         = 3,
    OMS_QUANTITY        = 4,
    OMS_STATUS          = 5,
    OMS_TRAN_NO         = 8,
    OMS_ACCOUNT         = 10,
    OMS_SIDE            = 11,
    OMS_BID_SIZE        = 16,
    OMS_VOLUME          = 17,
    OMS_OPEN_IN         = 18,
    OMS_OFFER_SIZE      = 19,
    OMS_EXCHANGE        = 20,
    OMS_NAME            = 21,
    OMS_PRODTYPE        = 22,
    OMS_CURRENCY        = 23,
    OMS_LOTSIZE         = 24,
    OMS_FREE_TEXT       = 25,
    OMS_UmmdsYMBOL      = 26,
    OMS_STRIKE_PRC      = 27,
    OMS_PUTCALL         = 28,
    OMS_MATURITY        = 29,
    OMS_ISIN            = 30,
    OMS_PREV_CLOSE      = 31,
    OMS_LOW             = 32,
    OMS_TIME            = 33,
    OMS_CHI_NAME        = 36,
    OMS_HIGH            = 37,
    OMS_TURNOVER        = 38,
    OMS_ERRORCODE       = 39,
    OMS_INSTRUCT        = 40,
    OMS_TRADETYPE       = 43,
    OMS_NETCHANGE       = 48,
    OMS_BID_SIZE_2      = 51,
    OMS_BID_SIZE_3      = 52,
    OMS_BID_SIZE_4      = 53,
    OMS_BID_SIZE_5      = 54,
    OMS_BID_QUEUE_1     = 55,
    OMS_BID_QUEUE_2     = 56,
    OMS_BID_QUEUE_3     = 57,
    OMS_BID_QUEUE_4     = 58,
    OMS_BID_QUEUE_5     = 59,
    OMS_ASK_SIZE_2      = 61,
    OMS_ASK_SIZE_3      = 62,
    OMS_ASK_SIZE_4      = 63,
    OMS_ASK_SIZE_5      = 64,
    OMS_ASK_QUEUE_1     = 65,
    OMS_ASK_QUEUE_2     = 66,
    OMS_ASK_QUEUE_3     = 67,
    OMS_ASK_QUEUE_4     = 68,
    OMS_ASK_QUEUE_5     = 69,
    OMS_SPREAD          = 73,
    OMS_USER_REF        = 74,
    OMS_EXCH_MARKET     = 75,
    OMS_BID_PRICE_2     = 81,
    OMS_BID_PRICE_3     = 82,
    OMS_BID_PRICE_4     = 83,
    OMS_BID_PRICE_5     = 84,
    OMS_ASK_PRICE_2     = 91,
    OMS_ASK_PRICE_3     = 92,
    OMS_ASK_PRICE_4     = 93,
    OMS_ASK_PRICE_5     = 94,
    OMS_CCASS           = 100,
    OMS_SHORTSELL       = 101,
    OMS_YIELD           = 102,
    OMS_CONVERSION_RATIO= 104,
    OMS_TRADE_1         = 110,
    OMS_TRADE_2         = 111,
    OMS_TRADE_3         = 112,
    OMS_TRADE_4         = 113,
    OMS_TRADE_5         = 114,
    OMS_BOND_ACCRUEDINTEREST = 118,
    OMS_BID_IDS         = 120,
    OMS_ASK_IDS         = 121,
    OMS_OPEN_PRICE      = 133,
    OMS_TRADE_DATE      = 134,
    OMS_LINKED_STOCK    = 135,
    OMS_CLOSE_SETTLEMENT= 137,
    OMS_DUMMY_STOCK     = 140,
    OMS_SERIESID        = 141,
    OMS_NEWS_SUBJECT    = 150,
    OMS_NEWS_LANGUAGE   = 151,
    OMS_FIRSTROW        = 200,
    OMS_GB_NAME         = 505,
    OMS_CONTRACT_SIZE   = 504,
    OMS_STAMPDUTY       = 403,
    OMS_SYSTEMREF       = 457,
    OMS_SOURCE_TIME     = 1100,
    OMS_VWAP            = 2014,
    MM_BID_QUANTITY     = 2007,
    MM_ASK_QUANTITY     = 2008,
    OMS_LP_BROKERS      = 3200,
    OMS_LISTING_DATE    = 3203,
    OMS_DELISTING_DATE  = 3204,
    OMS_EFN_FLAG        = 3205,
    OMS_BASKET_WARRANT_STYLE = 3207,
    OMS_INDEX_STATUS    = 3208,
    OMS_INDEX_EAV       = 3211,
    OMS_INDEX_NETCHANGE_PCT  = 3214,
    OMS_INDEX_EXCEPTION_FLAG = 3215,
    OMS_CLOSING_TRADES  = 3218,
    OMS_BID_QUEUE_6     = 3136,
    OMS_BID_QUEUE_7     = 3137,
    OMS_BID_QUEUE_8     = 3138,
    OMS_BID_QUEUE_9     = 3139,
    OMS_BID_QUEUE_10    = 3140,
    OMS_ASK_QUEUE_6     = 3146,
    OMS_ASK_QUEUE_7     = 3147,
    OMS_ASK_QUEUE_8     = 3148,
    OMS_ASK_QUEUE_9     = 3149,
    OMS_ASK_QUEUE_10    = 3150,
    OMS_BID_SIZE_6      = 3155,
    OMS_BID_SIZE_7      = 3156,
    OMS_BID_SIZE_8      = 3157,
    OMS_BID_SIZE_9      = 3158,
    OMS_BID_SIZE_10     = 3159,
    OMS_ASK_SIZE_6      = 3165,
    OMS_ASK_SIZE_7      = 3166,
    OMS_ASK_SIZE_8      = 3167,
    OMS_ASK_SIZE_9      = 3168,
    OMS_ASK_SIZE_10     = 3169,
    OMS_BID_PRICE_6     = 3180,
    OMS_BID_PRICE_7     = 3181,
    OMS_BID_PRICE_8     = 3182,
    OMS_BID_PRICE_9     = 3183,
    OMS_BID_PRICE_10    = 3184,
    OMS_ASK_PRICE_6     = 3190,
    OMS_ASK_PRICE_7     = 3191,
    OMS_ASK_PRICE_8     = 3192,
    OMS_ASK_PRICE_9     = 3193,
    OMS_ASK_PRICE_10    = 3194,
    OMS_COUPON_RATE     = 3403,
    OMS_VCM_FLAG        = 3500,
    OMS_VCM_START_TIME  = 3501,
    OMS_VCM_END_TIME    = 3502,
    OMS_VCM_REF_PRICE   = 3503,
    OMS_VCM_LOWER_PRICE = 3504,
    OMS_VCM_UPPER_PRICE = 3505,
    OMS_CAS_FLAG        = 3510,
    OMS_CAS_REF_PRICE   = 3511,
    OMS_CAS_LOWER_PRICE = 3512,
    OMS_CAS_UPPER_PRICE = 3513,
    OMS_ORDER_IMBAL_SIDE= 3514,
    OMS_ORDER_IMBAL_QTY = 3515,
    OMS_IEP             = 3516,
    OMS_IEV             = 3517,
    OMS_LEG_COUNT       = 542,
    OMS_LEG_RATIO       = 543,
    OMS_LEG_SYMBOLS     = 544,
};

} // namespace tradeengine::hkex
